export const FAKE_POPULARS = [
  {
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 374.462,
    first_air_date: "2011-04-17",
    vote_average: 8.439,
    vote_count: 21468,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/7gbmM2NWcqZONbp65HUWDf4wr0Q.jpg",
    id: 88040,
    name: "Given",
    original_language: "ja",
    original_name: "ギヴン",
    overview:
      "Tightly clutching his Gibson guitar, Mafuyu Satou steps out of his dark apartment to begin another day of his high school life. While taking a nap in a quiet spot on the gymnasium staircase, he has a chance encounter with fellow student Ritsuka Uenoyama, who berates him for letting his guitar's strings rust and break. Noticing Uenoyama's knowledge of the instrument, Satou pleads for him to fix it and to teach him how to play. Uenoyama eventually agrees and invites him to sit in on a jam session with his two band mates: bassist Haruki Nakayama and drummer Akihiko Kaji.",
    poster_path: "/lTP5yFKt2wzv8vM4EheNgIejEVu.jpg",
    media_type: "tv",
    genre_ids: [16, 18],
    popularity: 22.984,
    first_air_date: "2019-07-12",
    vote_average: 8.6,
    vote_count: 697,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 234.416,
    first_air_date: "2016-07-15",
    vote_average: 8.628,
    vote_count: 15837,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 374.462,
    first_air_date: "2011-04-17",
    vote_average: 8.439,
    vote_count: 21468,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
    id: 93405,
    name: "Squid Game",
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    media_type: "tv",
    genre_ids: [10759, 9648, 18],
    popularity: 140.456,
    first_air_date: "2021-09-17",
    vote_average: 7.835,
    vote_count: 12841,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg",
    id: 60059,
    name: "Better Call Saul",
    original_language: "en",
    original_name: "Better Call Saul",
    overview:
      'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
    poster_path: "/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 143.027,
    first_air_date: "2015-02-08",
    vote_average: 8.6,
    vote_count: 4199,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    id: 71446,
    name: "Money Heist",
    original_language: "es",
    original_name: "La Casa de Papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 124.233,
    first_air_date: "2017-05-02",
    vote_average: 8.26,
    vote_count: 17695,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 262.887,
    first_air_date: "2013-12-02",
    vote_average: 8.7,
    vote_count: 8395,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 242.41,
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 12029,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/33j33midGw49BBxiqlNZeZ6PZ0O.jpg",
    id: 85271,
    name: "WandaVision",
    original_language: "en",
    original_name: "WandaVision",
    overview:
      "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.",
    poster_path: "/frobUz2X5Pc8OiVZU8Oo5K3NKMM.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 18],
    popularity: 56.171,
    first_air_date: "2021-01-15",
    vote_average: 8.269,
    vote_count: 11177,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/sccDflItNho4OiHkzpiDxB2fUFw.jpg",
    id: 1418,
    name: "The Big Bang Theory",
    original_language: "en",
    original_name: "The Big Bang Theory",
    overview:
      "Physicists Leonard and Sheldon find their nerd-centric social circle with pals Howard and Raj expanding when aspiring actress Penny moves in next door.",
    poster_path: "/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 122.72,
    first_air_date: "2007-09-24",
    vote_average: 7.879,
    vote_count: 10130,
    origin_country: ["US"],
  },
];
